[build]
  command = "npm run build"
  publish = ".next" # ✅ out değil, .next olacak

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"